# Generated by Django 4.2.5 on 2024-02-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='date_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
